# These are supported funding model platforms

github: 6banlaobanzhang
custom: ['https://space.bilibili.com/449597750' ,'https://ghproxy.com/https://raw.githubusercontent.com/6banlaobanzhang/65-Save-Backup/README%E4%B8%93%E7%94%A8/mm_reward_qrcode_1661277326607.png']
