name: 存档中的建筑设计问题（现实中有但存档中无）
description: 如果你发现现实中有某个建筑但存档中没有，请在此提交Issues。
title: "[现实中有但存档中无] 我的标题"
assignees: 6banlaobanzhang
labels:
  - "存档与实地不符"
body:
- type: markdown
  attributes: 
    value: |
      ## 写在开头
      🚨 请务必完整填写下面的内容，如果缺少必要的信息，UP可能会直接关闭问题 🚨
      
- type: textarea
  id: description
  validations:
    required: true
  attributes:
     label: 描述
     description: 请简短地描述存档中的问题

- type: textarea
  id: repro-steps
  validations:
    required: true
  attributes:
     label: 建筑应该存在的位置
     render: plain text
     description: 

- type: textarea
  id: expected-behavior
  validations:
    required: true
  attributes:
     label: 预期行为
     description: 简要描述你希望看到什么样的结果
     
- type: textarea
  id: screenshots
  attributes:
     label: 截图
     description: 提交截图更有助于我们分析问题

- type: textarea
  id: additional-context
  attributes:
     label: 备注
     description: 添加你认为有必要的信息

- type: dropdown
  id: contribution
  attributes:
     label: 【暂停使用】投影模组蓝图/结构文件上传区域
     description: 如果你已经建造完毕，你可以使用投影模组或结构方块，将蓝图或结构文件导出并上传。
